apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lzjf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-lzjf@sha256:40f0c1efe682b7c67df27e23d048cad24f941ab25a2e2981b1cf3d23b0811504
        name: my-nodejs
        resources: {}
status: {}
